### ISSUE TITLE
No search progress when indexing

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/ScreenshotGo#584] opened 2019-02-25 06:27 UTC
Description:
Search progress should be shown during indexing

Pre-requisite:
some images which are not indexed yet. More than 200 will be easier for observing.

Step:
1. Launch ScreenshotGo
2. Tap on Search button
3. type "tr" for searching

Expected result:
3. Indexing progress is shown on the screen

Actual Result:
3. No progressing information, but a user can observe the search result is increasing (if fit)

Build no: 0.8 (1055)
Device: Nexus 5 (Android 6.0)

**Comment by Conjuror** [comment] 2019-02-25 06:34
Same issue on the same build with Device: Redmi 5 plus (Android 8.0)

**Comment by weslyhuang** [comment] 2019-02-27 06:51
tried and seems hard to repro., also by design we don't want to explicitly show the "indexing work" to users, thus P1 looks good to me.

**Comment by Conjuror** [comment] 2019-02-27 06:56
An update of reproduce steps

Pre-requisite:
500+ non-indexed screenshots (it will be easier to observer if more)

Step:
1. Launch ScreenshotGo
2. Tap search and search some words
3. Tap back key
4. Tap home key 
5. Launch another app and play around (not necessary to be long, one or two actions should be enough)
6. Tap home key
7. Launch ScreenshotGo
8. Tap search and search some words

Expected Result:
2. Information of indexing is shown
8. information of indexing is shown

Actual Result:
8. Information of indexing is gone

Be aware that even there's no indexing information, it's still indexing in the background by observing the results ScreenshotGo found.

DuT: Redmi 5 plus (Android 8.0)
Build: 0.8 (1081)

**Comment by weslyhuang** [comment] 2019-03-08 07:32
P0 as Sprint#7's nice to have.

**Comment by benjamin-cheng** [comment] 2019-03-11 09:54
Cannot reproduce this issue, it should already be fixed in the latest release build(1113).

**Closed by benjamin-cheng** 2019-03-11 09:54 UTC
Labels: 1. P0, S2
