### ISSUE TITLE
Can not extract text from long screeenshots (from Rocket) 

### ISSUE THREAD

**Issue by StellaTseng** [mozilla-tw/ScreenshotGo#269] opened 2018-09-27 02:52 UTC
![screenshot_2018-09-27-10-49-03](https://user-images.githubusercontent.com/34704183/46120701-53d70d00-c243-11e8-8396-63a67ae781ca.png)

**Comment by weslyhuang** [comment] 2018-09-27 03:03
@cynthiatang would you help check if this is same as #183? If yes then set it as P1, too. Thanks.

**Comment by weslyhuang** [comment] 2018-09-28 02:41
could be P0 if toast not shown as intended.

**Comment by weslyhuang** [comment] 2018-09-28 03:33
confirmed with Stella there is toast. The OCR result would not be good due to special size screenshot (as expected). So close this issue.

however QA did find another minor bug while retesting, so created # for tracking.

**Closed** 2018-09-28 03:34 UTC
Labels: P0, detail-view, qa wanted
